### ISSUE TITLE
Feature Request: EA Validator - Store queries into EA elements 

### ISSUE THREAD

**Issue by brothercorvo** [GeertBellekens/Enterprise-Architect-Toolpack#121]
As we know, in many organizations is difficult to deploy local code to users. as an alternative, the EA validator could save the queries into a stereotyped EA element.

**Comment by GeertBellekens** [comment]
In fact it's already possible to create rules that are stored in the model.
I should probably document it a bit better. The code was added in this [commit](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/commit/2707c9e09c00f5efacb612fd3bb0554fbee14fa2)
In the settings you can select a package in the model instead of a location on disk. It will read the notes of any artifact that is stored in that package. Subpackages are treated the same as subfolders
![image](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/assets/615534/b03b4b36-bbc6-44be-9be9-904fedb05160)

**Comment by brothercorvo** [comment]
that's great!
however it's not working properly for me.
As soon I set the configuration to check a package I only get an empty list
![image](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/assets/60719165/96c12626-36db-4ec1-b4dc-389e3e99c0a2)
on that package I have a modelDocument with the notes set to the XML
![image](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/assets/60719165/e2a5ecab-25db-4716-b9bd-d0b0500bb7b4)

**Comment by GeertBellekens** [comment]
it has to be an element of type **artifact**

**Comment by brothercorvo** [comment]
I can confirm that works setting the type as artifact and the XML into the notes of the element.
thank you !
